/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.object_onepiece;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import it.unibo.object_onepiece.model.Utils.CardinalDirection;
import it.unibo.object_onepiece.model.Utils.*;

public class UtilsTest {

    private Position p = new Position(4, 2);

    @Test void testMoveTowards() throws ClassNotFoundException {
        assertEquals(new Position(4, 3), p.moveTowards(CardinalDirection.EAST));
        assertEquals(new Position(4, 1), p.moveTowards(CardinalDirection.WEST));
        assertEquals(new Position(3, 2), p.moveTowards(CardinalDirection.NORTH));
        assertEquals(new Position(5, 2), p.moveTowards(CardinalDirection.SOUTH));
    }

    @Test void testDistanceFrom() throws ClassNotFoundException {
        assertEquals(3, p.distanceFrom(new Position(4, 5)));
        assertEquals(5, p.distanceFrom(new Position(9, 2)));
        assertNotEquals(3, p.distanceFrom(new Position(4, 4)));
        assertNotEquals(5, p.distanceFrom(new Position(7, 9)));
    }

    @Test void testSum() throws ClassNotFoundException {
        assertEquals(new Position(5, 3), p.sum(new Position(1, 1)));
        assertEquals(new Position(7, 6), p.sum(new Position(3, 4)));
        assertEquals(new Position(5, 0), p.sum(new Position(1, -2)));
        assertEquals(new Position(10, 7), p.sum(new Position(6, 5)));
    }

    @Test void testIsInlineWith() throws ClassNotFoundException {
        assertEquals(true, p.isInlineWith(new Position(4, 5), CardinalDirection.NORTH));
    }
}
